### ISSUE TITLE
lzw-ab output incompatible with ncompress and other LZW decompressors

### ISSUE THREAD

**Issue by despoa** [dbry/lzw-ab#3]
The output from lzw-ab can now be only decompressed by lzw-ab itself, not other established LZW decompressors such as ncompress and 7-Zip. I assume this is due to the new improvements to compression algorithm in lzw-ab.

**Comment by andrew-aladev** [comment]
Hello, please try to use [lzws](https://github.com/andrew-aladev/lzws), its main goal is to provide compatibility with all `Content-Encoding: compress` processors such as `ncompress`. `lzws` can be compiled with dictionary algorithm from `lzw-ab` using `-DLZWS_COMPRESSOR_DICTIONARY="linked-list"`. For now `lzws` is available for `GNU/Linux`, `FreeBSD` and `MinGW` only. `Cygwin` and `MSVC` support will be added soon.

**Comment by andrew-aladev** [comment]
PS if you are interested in implementing compatibility layer in `lzw-ab`, please review [the following issue](https://github.com/vapier/ncompress/issues/5).

**Comment by dbry** [comment]
> The output from lzw-ab can now be only decompressed by lzw-ab itself, not other established LZW decompressors such as ncompress and 7-Zip. I assume this is due to the new improvements to compression algorithm in lzw-ab.

You are correct. There are two features that allow LZW-AB to compress better than standard LZW compressors: the `adjusted binary` part and the new feature I recently added that continuously recycles dictionary entries. Of course these make the output incompatible with existing compressors.

However, I never really intended this to be a replacement for those other compressors. It was mean to be used in an embedded system or some other closed environment where something small was desired. Or, because it's so simple, it could be used as a starting point for another compression experiment or just to learn how LZW works.
