### ISSUE TITLE
Is there something wrong here? 

### ISSUE THREAD

**Issue by Y-JESSE** [dbry/lzw-ab#4]
https://github.com/dbry/lzw-ab/blob/bfb62d93180d32713757c5692ef3d0efc8ef413e/lzwlib.c#L206
If this condition is true, it will consume a dictionary array space, but the variable available_entries is not reduced by one. Or am I understanding it wrong?

**Comment by dbry** [comment]
The `available_entries` does not just refer to the number of unused dictionary entries. It only refers to dictionary entries that have not been used in longer strings (and are therefore recyclable). So `available_entries` is only decremented when we set the `first_reference` of a dictionary entry (which means that entry has been referenced by another entry). Similarly, we only increment `available_entries` when we clear the `first_reference` field of an entry because it was referencing an entry we just recycled (which means it no longer references a longer string, and can potentially be recycled next time through).

The `available_entries` is not strictly needed for this compressor to work because there will always be at least one available dictionary entry to recycle (the last one we created _cannot_ be part of a longer string yet). However with some data we might get into a situation where we have very few available entries (or even just one) and so we would be quickly cycling through just those few. This seemed like not a good thing to me, but I don't actually know how bad or common it is. But I decided that preventing it would be worthwhile, and the only way to do that without doing a lot of dictionary scanning would be to keep track of the number of entries that can be recycled.

Thanks for the question and I hope this makes sense!

**Comment by Y-JESSE** [comment]
Thank you for your answer. I have not understood the real function of the variable available_entries, so I have not fully understood the dictionary recovery algorithm you wrote. When you say this, I understand these codes.
Thanks again for your help.
